Add `input_from` to read input hashes from a previous step

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -3,15 +3,17 @@
 COPPERMIND_REPO="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" &> /dev/null && pwd )"
 source "${COPPERMIND_REPO}/lib/common.sh"
 
-# Start hashing up our input glob patterns
+# Start hashing up our input glob patterns, unless we've already been supplied one by `input_from`
+if [[ ! -v "BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH" ]]; then
+    INPUT_TREEHASHES=()
+    for PATTERN in "${INPUT_PATTERNS[@]}"; do
+        INPUT_TREEHASHES+=( "$(collect_glob_pattern "${PATTERN}" | calc_treehash)" )
+    done
 
-INPUT_TREEHASHES=()
-for PATTERN in "${INPUT_PATTERNS[@]}"; do
-    INPUT_TREEHASHES+=( "$(collect_glob_pattern "${PATTERN}" | calc_treehash)" )
-done
-
-# Hash all treehashes together to get full input hash
-export BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH=$(printf "%s" "${INPUT_TREEHASHES[@]}" | calc_shasum)
+    # Hash all treehashes together to get full input hash
+    export BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH=$(printf "%s" "${INPUT_TREEHASHES[@]}" | calc_shasum)
+    buildkite-agent meta-data set "coppermind-${BUILDKITE_STEP_KEY}-inputhash" "${BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH}"
+fi
 
 # Get listing of all files that exist with the given prefix
 S3_ROOT="s3://${S3_BUCKET}/${S3_PREFIX}/${BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH}"
@@ -30,4 +32,9 @@ if [[ ${#S3_LISTING[@]} -gt 0 ]]; then
             AWS_ACCESS_KEY_ID=${BUILDKITE_S3_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${BUILDKITE_S3_SECRET_ACCESS_KEY} aws s3 cp "s3://${S3_BUCKET}/${URL}" .
         fi
     done
+elif [[ -v "BUILDKITE_PLUGIN_COPPERMIND_INPUT_FROM" ]]; then
+    # If `input_from` was specified, we fail out if we can't find any artifacts
+    echo "ERROR: No previously-calculated artifacts found for '${BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH}'"
+    buildkite-agent annotate --style error "No previously-calculated artifacts found for '${BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH}'"
+    exit 1
 fi
